import 'package:drift/drift.dart';

import 'connection.dart';
import 'db_seeder.dart';
import 'entities/entities.dart';

// Generated by build_runner — one combined output file; table sources live in entities/.
part 'app_database.g.dart';

@DriftDatabase(
  tables: [
    Users,
    Tiers,
    Categories,
    Produits,
    StockLocations,
    MouvementsStock,
    Devis,
    DevisLignes,
    BonsCommandeClient,
    BonCommandeClientLignes,
    BonsLivraison,
    BonLivraisonLignes,
    PaiementsBonLivraison,
    Factures,
    FactureLignes,
    Avoirs,
    AvoirLignes,
    BonsCommande,
    BonCommandeLignes,
    BonsReception,
    BonReceptionLignes,
    FacturesFournisseurs,
    FactureFournisseurLignes,
    PaiementsFournisseurs,
    AvoirsFournisseurs,
    AvoirFournisseurLignes,
    TypesCharges,
    Charges,
    BonsCharge,
    BonChargeLignes,
    BonsDecharge,
    BonDechargeLignes,
    RemisesCaisse,
    AppSettings,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor]) : super(executor ?? openConnection());

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
      await _createCustomIndexesAndConstraints();
      await DbSeeder.seed(this);
    },
    onUpgrade: (m, from, to) async {
      if (from < 2) await _migrateSupplierPaymentsToBr();
      if (from < 3) await _migrateTierPhoneUnique();
    },
    beforeOpen: (details) async {
      if (!details.wasCreated) {
        await DbSeeder.removeLegacyDepotAdmin(this);
      }
    },
  );

  /// Supplier payments move from the facture fournisseur to the bon de
  /// réception, mirroring the ventes side where a payment hangs off the BL.
  ///
  /// A payment cannot be mapped back to a specific BR when its facture grouped
  /// several, so each one is attached to that facture's oldest BR: supplier
  /// totals are preserved exactly, only the per-BR split is approximate. A
  /// payment whose facture had no BR behind it (a facture of free catalog
  /// lines) has nowhere to go and is dropped.
  /// Test-only entry point for [_migrateSupplierPaymentsToBr], which
  /// `MigrationStrategy` otherwise only reaches on a real upgrade.
  Future<void> migrateSupplierPaymentsToBrForTest() =>
      _migrateSupplierPaymentsToBr();

  /// Test-only entry point for [_migrateTierPhoneUnique].
  Future<bool> migrateTierPhoneUniqueForTest() => _migrateTierPhoneUnique();

  /// Brings an existing database up to the `.unique()` now declared on
  /// `Tiers.telephone`. Fresh installs get it from `createAll`, so only
  /// databases created before the constraint need this step.
  ///
  /// The index is partial (`telephone <> ''`) on purpose: tiers created before
  /// the phone became mandatory all carry an empty string, and a full UNIQUE
  /// index cannot be built while they exist. Empty rows are the only ones left
  /// unenforced, and nothing can create one any more — `TiersService` requires
  /// a phone. This mirrors the existing partial index on `StockLocations`.
  ///
  /// Returns false — index not created — when legacy rows already share a
  /// non-empty phone. SQLite would refuse the whole migration and the app would
  /// not open, so the duplicates have to be resolved first; the service-level
  /// check in `TiersService` keeps protecting new rows until they are.
  Future<bool> _migrateTierPhoneUnique() async {
    final dupes = await _duplicateTierPhones();
    if (dupes.isNotEmpty) return false;
    await _createTierPhoneUniqueIndex();
    return true;
  }

  Future<List<String>> _duplicateTierPhones() async {
    final rows = await customSelect(
      "SELECT telephone FROM Tiers "
      "WHERE telephone <> '' "
      'GROUP BY telephone HAVING COUNT(*) > 1',
    ).get();
    return [for (final r in rows) r.read<String>('telephone')];
  }

  Future<void> _createTierPhoneUniqueIndex() => customStatement('''
    CREATE UNIQUE INDEX IF NOT EXISTS IX_Tiers_Telephone
    ON Tiers (telephone)
    WHERE telephone <> '';
  ''');

  Future<void> _migrateSupplierPaymentsToBr() async {
    await customStatement(
      'ALTER TABLE BonsReception ADD COLUMN est_payee INTEGER NOT NULL DEFAULT 0',
    );

    await customStatement('''
      CREATE TABLE PaiementsFournisseurs_new (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        bon_reception_id INTEGER NOT NULL
          REFERENCES BonsReception (id) ON DELETE CASCADE,
        date INTEGER NOT NULL,
        montant REAL NOT NULL,
        mode INTEGER NOT NULL DEFAULT 0,
        reference TEXT NOT NULL DEFAULT '',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        created_by_user_id INTEGER NULL
      )
    ''');

    await customStatement('''
      INSERT INTO PaiementsFournisseurs_new (
        id, bon_reception_id, date, montant, mode, reference,
        created_at, updated_at, created_by_user_id
      )
      SELECT
        p.id,
        (
          SELECT MIN(l.bon_reception_id)
          FROM FactureFournisseurLignes l
          WHERE l.facture_fournisseur_id = p.facture_fournisseur_id
            AND l.bon_reception_id IS NOT NULL
        ),
        p.date, p.montant, p.mode, p.reference,
        p.created_at, p.updated_at, p.created_by_user_id
      FROM PaiementsFournisseurs p
      WHERE EXISTS (
        SELECT 1 FROM FactureFournisseurLignes l
        WHERE l.facture_fournisseur_id = p.facture_fournisseur_id
          AND l.bon_reception_id IS NOT NULL
      )
    ''');

    await customStatement('DROP TABLE PaiementsFournisseurs');
    await customStatement(
      'ALTER TABLE PaiementsFournisseurs_new RENAME TO PaiementsFournisseurs',
    );
  }

  Future<void> _createCustomIndexesAndConstraints() async {
    await customStatement('''
      CREATE UNIQUE INDEX IF NOT EXISTS IX_StockLocations_UserId_Virtual
      ON StockLocations (user_id)
      WHERE is_virtual = 1;
    ''');

    await customStatement('''
      CREATE INDEX IF NOT EXISTS IX_MouvementsStock_Origine
      ON MouvementsStock (origine_type, origine_id);
    ''');
  }
}
