import 'package:drift/drift.dart';

import 'connection.dart';
import 'db_seeder.dart';
import 'entities/entities.dart';

// Generated by build_runner — one combined output file; table sources live in entities/.
part 'app_database.g.dart';

@DriftDatabase(tables: [
  Users,
  Tiers,
  Categories,
  Produits,
  StockLocations,
  MouvementsStock,
  Devis,
  DevisLignes,
  BonsCommandeClient,
  BonCommandeClientLignes,
  BonsLivraison,
  BonLivraisonLignes,
  PaiementsBonLivraison,
  Factures,
  FactureLignes,
  Avoirs,
  AvoirLignes,
  BonsCommande,
  BonCommandeLignes,
  BonsReception,
  BonReceptionLignes,
  FacturesFournisseurs,
  FactureFournisseurLignes,
  PaiementsFournisseurs,
  AvoirsFournisseurs,
  AvoirFournisseurLignes,
  TypesCharges,
  Charges,
  BonsCharge,
  BonChargeLignes,
  BonsDecharge,
  BonDechargeLignes,
  RemisesCaisse,
  AppSettings,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor]) : super(executor ?? openConnection());

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
          await _createCustomIndexesAndConstraints();
          await DbSeeder.seed(this);
        },
        onUpgrade: (m, from, to) async {
          // Future migrations go here.
        },
      );

  Future<void> _createCustomIndexesAndConstraints() async {
    await customStatement('''
      CREATE UNIQUE INDEX IF NOT EXISTS IX_StockLocations_UserId_Virtual
      ON StockLocations (user_id)
      WHERE is_virtual = 1;
    ''');

    await customStatement('''
      CREATE INDEX IF NOT EXISTS IX_MouvementsStock_Origine
      ON MouvementsStock (origine_type, origine_id);
    ''');
  }
}
